### PR TITLE
[Dependencies] Support react and react-dom 16 in peerDependencies

### PR DESCRIPTION
**Pull request by negativetwelve**
Hi there, thanks for creating this component! Using it in a project with React 16+ will cause this warning: 

```
warning "react-ios-switch@0.1.10" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".
```

This PR updates the peerDependencies to satisfy this warning + the component seems to be compatible with 16 (unless I'm mistaken).

Thanks for reviewing!

### CODE REVIEW

**Comment by negativetwelve** [comment]
hey there @mking-clari, noticed you were last active on this repo. Would you be able to review this PR and possibly merge + publish a new release? thanks!

**Comment by mking-clari** [comment]
@negativetwelve does it still work if you put `>=0.14.0`? prefer that if possible

**Comment by negativetwelve** [comment]
Yep! Went ahead and made the change + squashed commits. Here's a screenshot:

image
 
thnaks @mking-clari!

**Comment by negativetwelve** [comment]
hey there @mking-clari, any update on this? thanks for taking a look!

**Comment by mking-clari** [comment]
thanks @negativetwelve

**Comment by negativetwelve** [comment]
no problem, thank you!

**Pull request merged**
